apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "92"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"api"},"name":"api","namespace":"piloto-portal-cidadao"},"spec":{"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/name":"api"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app.kubernetes.io/name":"api"}},"spec":{"containers":[{"env":[{"name":"ASPNETCORE_ENVIRONMENT","value":"Production"}],"envFrom":[{"secretRef":{"name":"api"}}],"image":"registry.tce.ro.gov.br/$PROJETO:$TAG","name":"api","resources":{"limits":{"cpu":"4","memory":"8Gi"},"requests":{"cpu":"1","memory":"500Mi"}}}],"restartPolicy":"Always"}}}}
    kubectl.kubernetes.io/restartedAt: "2025-04-23T13:00:44+00:00"
  labels:
    app.kubernetes.io/name: api
  name: api
  namespace: piloto-portal-cidadao
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: 2025-04-23T15:10:31
        openshift.openshift.io/restartedAt: "2025-05-14T14:26:53.358Z"
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: api
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: api
            - configMapRef:
                name: api
          image: registry-ocp.tcero.tc.br/piloto-portal-cidadao/api:production
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          name: api
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "4"
              memory: 8Gi
            requests:
              cpu: "1"
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
