apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "42"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"identity"},"name":"identity","namespace":"piloto-portal-cidadao"},"spec":{"replicas":0,"selector":{"matchLabels":{"app.kubernetes.io/name":"identity"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app.kubernetes.io/name":"identity"}},"spec":{"containers":[{"env":[{"name":"ASPNETCORE_ENVIRONMENT","value":"Production"}],"envFrom":[{"secretRef":{"name":"identity"}}],"image":"registry.tce.ro.gov.br/$PROJETO:$TAG","name":"identity","resources":{"limits":{"cpu":"2","memory":"1Gi"},"requests":{"cpu":"250m","memory":"50Mi"}}}],"restartPolicy":"Always"}},"test":false,"triggers":[{"type":"ConfigChange"},{"imageChangeParams":{"automatic":true,"containerNames":["identity"],"from":{"kind":"ImageStreamTag","name":"identity:$TAG"}},"type":"ImageChange"}]}}
  labels:
    app.kubernetes.io/name: identity
  name: identity
  namespace: piloto-portal-cidadao
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: identity
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        openshift.openshift.io/restartedAt: "2025-04-15T16:00:00.850Z"
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: identity
    spec:
      containers:
        - env:
            - name: ASPNETCORE_Kestrel__Certificates__Default__Password
              valueFrom:
                secretKeyRef:
                  key: secret_certificate
                  name: identity
          envFrom:
            - secretRef:
                name: identity
            - configMapRef:
                name: identity
          image: image-registry.openshift-image-registry.svc:5000/piloto-portal-cidadao/identity:development
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          name: identity
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "2"
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 50Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /app/.aspnet/https
              name: identity-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: identity-volume
          secret:
            defaultMode: 420
            secretName: identity-certificate
