kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: identity
  namespace: piloto-portal-cidadao
  uid: c2cde598-6481-4398-9b4b-77525d14ba65
  resourceVersion: '92645548'
  creationTimestamp: '2025-03-27T19:27:14Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: autoscaling/v2
      time: '2025-04-08T14:11:18Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:maxReplicas': {}
          'f:metrics': {}
          'f:minReplicas': {}
          'f:scaleTargetRef':
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: autoscaling/v2
      time: '2025-05-13T13:43:34Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            .: {}
            'k:{"type":"AbleToScale"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"ScalingActive"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"ScalingLimited"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:currentMetrics': {}
          'f:currentReplicas': {}
          'f:desiredReplicas': {}
          'f:lastScaleTime': {}
      subresource: status
spec:
  scaleTargetRef:
    kind: Deployment
    name: identity
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
status:
  lastScaleTime: '2025-05-09T17:39:08Z'
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
    - type: Resource
      resource:
        name: cpu
        current:
          averageValue: 18m
          averageUtilization: 7
  conditions:
    - type: AbleToScale
      status: 'True'
      lastTransitionTime: '2025-03-27T19:27:29Z'
      reason: ReadyForNewScale
      message: recommended size matches current size
    - type: ScalingActive
      status: 'True'
      lastTransitionTime: '2025-04-15T16:30:25Z'
      reason: ValidMetricFound
      message: the HPA was able to successfully calculate a replica count from cpu resource utilization (percentage of request)
    - type: ScalingLimited
      status: 'False'
      lastTransitionTime: '2025-05-13T13:35:19Z'
      reason: DesiredWithinRange
      message: the desired count is within the acceptable range
