apiVersion: v1
data:
  secret_api_db: dWEkI2pXOWY4YmEkIzlG
  secret_api_db_pgsql: YSQjOUZ1YSQjaldhMmE5OWY4Yg==
  secret_certificate: dHJpYnVuYWw=
  secret_db_pgsql_pce: OGU0NzRiOTFkNTUzYQ==
  secret_identity_db: YSQjOUZ1YSQjaldhMmE5OWY4Yg==
  secret_identity_db_pgsql: YSQjOUZ1YSQjaldhMmE5OWY4Yg==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"name":"identity","namespace":"piloto-portal-cidadao"},"stringData":{"secret_api_db":"","secret_api_db_pgsql":"","secret_certificate":"","secret_db_pgsql_pce":"admin ''","secret_identity_db":"","secret_identity_db_pgsql":""}}
  name: identity
type: Opaque
